export const REGISTER_PLAYER_REQUESTED = "REGISTER_PLAYER_REQUESTED";
export const FETCH_GAME_STATUS = "FETCH_GAME_STATUS";
export const UPDATE_GAME_STATUS = "UPDATE_GAME_STATUS";
export const FETCH_LOBBY_STATUS = "FETCH_LOBBY_STATUS";
export const MAKE_MOVE = "MAKE_MOVE";
export const INVALID_MOVE = "INVALID_MOVE";
